on:
  release:
    types: [created]

name: Release
jobs:
  release-linux-amd64:
    name: build articats for linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Create tag artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: Release

      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          ldflags: "-X 'main.Version=v${{github.ref_name}}'"


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker (Release Tag)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.JTLEA_DOCKER_USERNAME }}
          password: ${{ secrets.JTLEA_DOCKER_SECRET }}
          repository: jtlsoftware/goprometrics
          tag_with_ref: true

      - name: Push to Docker (Latest)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.JTLEA_DOCKER_USERNAME }}
          password: ${{ secrets.JTLEA_DOCKER_SECRET }}
          repository: jtlsoftware/goprometrics
          tags: "latest"
